# Generated by Django 3.1 on 2021-12-29 15:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211229_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='convo',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
