# Generated by Django 3.1 on 2021-12-29 15:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_convo_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convo',
            name='members',
            field=models.ManyToManyField(related_name='convos', to=settings.AUTH_USER_MODEL),
        ),
    ]
