# Generated by Django 3.1 on 2021-12-30 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20211229_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sentAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
