# Generated by Django 3.1 on 2021-12-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20211230_0354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sentAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
