# Generated by Django 3.1 on 2022-01-02 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20211230_0356'),
    ]

    operations = [
        migrations.AddField(
            model_name='convo',
            name='timeOfLastMsg',
            field=models.DateTimeField(auto_now_add=True, default='2022-01-01T23:45:34.685802Z'),
            preserve_default=False,
        ),
    ]
