# Generated by Django 3.1 on 2022-01-02 04:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_convo_timeoflastmsg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convo',
            name='timeOfLastMsg',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
